routes/web.php
<?php

Route::get('/', function () {
    return view('templates/home');
})->name('home');

Route::resource('/users', 'UserController');
Route::get('/user', 'UserController@search')->name('users.search');

Route::resource('/categories', 'CategoryController');
Route::get('/category', 'CategoryController@search')->name('categories.search');

Route::resource('/books', 'BookController');
Route::get('/book', 'BookController@search')->name('books.search');

Route::resource('/orders', 'OrderController');
Route::get('/order', 'OrderController@search')->name('orders.search');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'description', 'author', 'publisher', 'price', 'stock'
    ];

    public function category()     
    {         
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Book;
use App\Category;  

class BookController extends Controller
{
    public function index()
    {
        $books = Book::paginate(5);
        return view('books.index',compact('books'));
    }

    public function create()
    {
        $categories =Category::all();
        return view('books.create',['categories'=>$categories]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required|max:100|unique:books',             
            'description'=>'required|max:200',             
            'author'=>'required',                   
            'publisher'=>'required',       
            'price'=> 'required',            
            'stock'=> 'required',  
            'category'=> 'required',
            'cover'=>'required|mimes:jpg,jpeg,png,bmp', 
        ]); 

        $new_book = new Book();         
        $new_book->title = $request->get('title');
        $new_book->description = $request->get('description');         
        $new_book->author = $request->get('author');         
        $new_book->publisher = $request->get('publisher');         
        $new_book->price = $request->get('price'); 
        $new_book->stock = $request->get('stock');         
        if ($request->file('cover')) {             
            $file = $request->file('cover')->store('covers','public');
            $new_book->cover = $file;         
        }         
        $new_book->save(); 
        
        $new_book->category()->attach($request->get('category'));

        return redirect()->route('books.create')->with('status','Book Succesfully Created');     
    }

    public function show($id)
    {
        $book = Book::findOrFail($id); 
        return view('books.show',['book'=>$book]); 
    }

    public function edit($id)
    {
        $categories =Category::all();
        $book = Book::findOrFail($id);  
        return view('books.edit',['book'=>$book,'categories'=>$categories]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([           
            'description'=>'required|max:200',             
            'author'=>'required',                    
            'publisher'=>'required',         
            'price'=> 'required',            
            'stock'=> 'required',  
            'category'=> 'required',
        ]); 
        $update_book = Book::findOrFail($id);         
        $update_book->description = $request->get('description');         
        $update_book->author = $request->get('author');        
        $update_book->publisher = $request->get('publisher');        
        $update_book->price = $request->get('price'); 
        $update_book->stock = $request->get('stock');
        if ($request->file('cover')) {             
            if ($update_book->cover && file_exists(storage_path('app/public/'.$update_book->cover))) {                 
                Storage::delete('public/'.$update_book->cover);             
            }             
            $file = $request->file('cover')->store('covers','public');
            $update_book->cover = $file;         
        }         
        $update_book->save();      
        
        $update_book->category()->sync($request->get('category'));

        return redirect()->route('books.edit',['id'=>$id])->with('status','Book succesfully updated');     
    
    }

    public function destroy($id)
    {
        $book = Book::findOrFail($id);        
        if ($book->cover && file_exists(storage_path('app/public/'.$book->cover))) {             
            Storage::delete('public/'.$book->cover);         
        }         
        $book->delete();        
        return redirect()->route('books.index')->with('status', 'Book Successfully deleted');      
    }

    public function search(Request $request)
    {
        $books = Book::when($request->keyword, function ($query) use ($request) {
            $query->where('title', 'like', "%{$request->keyword}%");
        })->paginate(5);

        $books->appends($request->only('keyword'));

        return view('books.index', compact('books'));
    }
}

resources/views/books/create.blade.php
@extends('templates.home')
@section('title')
    Create Book
@endsection
@section('content')
    <div class="container" >
        <h3>Create Book</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">     
                <strong>{{ session('status') }}</strong>  
                <button type="button" class="close" data-dismiss="alert" arialabel="Close">       
                    <span aria-hidden="true">&times;</span> 
                </button>             
            </div>         
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Book</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('books.store') }}" class="form-group" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="title" >Title</label>
                            </div>
                            <div class="col-md-8">
                            <input value="{{ old('title') }}" type="text" class="form-control {{ $errors->first('title')? "is-invalid": "" }}" name="title" id="title">        
                                <div class="invalid-feedback">   
                                    {{$errors->first('title')}} 
                                </div>
                            </div>     
                        </div>
                        <br>
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="author">Author</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('author') }}" type="text" class="form-control {{ $errors->first('author')? "is-invalid": "" }}" name="author" id="author">        
                                <div class="invalid-feedback">   
                                    {{$errors->first('author')}} 
                                </div>
                            </div>     
                        </div>
                        <br>
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="publisher">Publisher</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('publisher') }}" type="text" class="form-control {{ $errors->first('publisher')? "is-invalid": "" }}" name="publisher" id="publisher">        
                                <div class="invalid-feedback">   
                                    {{$errors->first('publisher')}} 
                                </div>
                            </div>     
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="description">Description</label>
                            </div>
                            <div class="col-md-8">
                                <textarea name="description" class="form-control {{$errors->first('description') ? "is-invalid": ""}}" id="description" cols="20" rows="5">{{ old('description') }}</textarea>
                                <div class="invalid-feedback">              
                                    {{$errors->first('description')}}          
                                </div>                            
                            </div> 
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="price">Price</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('price') }}" type="number" class="form-control {{ $errors->first('price')? "is-invalid": "" }}" name="price" id="price">        
                                <div class="invalid-feedback">   
                                    {{$errors->first('price')}} 
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="stock">Stock</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('stock') }}" type="number" class="form-control {{ $errors->first('stock')? "is-invalid": "" }}" name="stock" id="stock">        
                                <div class="invalid-feedback">   
                                    {{$errors->first('stock')}} 
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="category">Category</label>
                            </div>
                            <div class="col-md-8">    
                                <select multiple='multiple' name="category[]" id="category" class="form-control {{$errors->first('category') ? "is-invalid": ""}}">        
                                    <option value="">Select Category</option>           
                                    @foreach ($categories as $category)    
                                        <option value="{{ $category->id }}">{{ $category->category_name }}</option> 
                                    @endforeach  
                                </select>
                                <div class="invalid-feedback">
                                    {{$errors->first('category')}}   
                                </div>                 
                            </div>    
                        </div>
                        <br>
                        <div class="row">
                            <div class="input-group mb-3">
                                <div class="col-md-3 text-primary">
                                    Cover
                                </div>
                                <div class="col-md-8">
                                    <div class="custom-file">        
                                        <label for="cover" class="custom-file-label">Cover</label>              
                                        <input type="file" class="custom-file-input {{$errors->first('cover') ? "is-invalid": ""}}" name="cover" id="cover">                  
                                        <div class="invalid-feedback">             
                                            {{$errors->first('cover')}}           
                                        </div>                                 
                                    </div>      
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Book
@endsection
@section('content')
    <div class="container" >
        <h3>Form Edit Book</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">          
                <strong>{{ session('status') }}</strong>       
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">       
                    <span aria-hidden="true">&times;</span>  
                </button>             
            </div>         
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>{{ $book['title'] }}</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('books.update',$book['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">                        
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="author" class="text-primary">Author</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control {{$errors->first('author') ? "is-invalid": ""}}" name="author" id="author" value="{{ old('author') ? old('author') : $book['author'] }}">                                 
                                <div class="invalid-feedback">                        
                                    {{$errors->first('author')}}              
                                </div>   
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="publisher" class="text-primary">Publisher</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control {{$errors->first('publisher') ? "is-invalid": ""}}" name="publisher" id="publisher" value="{{ old('publisher') ? old('publisher') : $book['publisher'] }}">                                 
                                <div class="invalid-feedback">                        
                                    {{$errors->first('publisher')}}              
                                </div>   
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="description" class="text-primary">Description</label>
                            </div>
                            <div class="col-md-8">
                                <textarea name="description" class="form-control {{$errors->first('description') ? "is-invalid": ""}}" id="description" cols="20" rows="5">{{ old('description') ? old('description') : $book['description'] }}</textarea>                  
                                <div class="invalid-feedback">   
                                    {{$errors->first('description')}}                 
                                </div>
                            </div> 
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="price" class="text-primary">Price</label>
                            </div>
                            <div class="col-md-8">
                                <input type="number" class="form-control {{$errors->first('price') ? "is-invalid": ""}}" name="price" id="price" value="{{ old('price') ? old('price') : $book['price'] }}">                                 
                                <div class="invalid-feedback">                        
                                    {{$errors->first('price')}}              
                                </div>   
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="stock" class="text-primary">Stock</label>
                            </div>
                            <div class="col-md-8">
                                <input type="number" class="form-control {{$errors->first('stock') ? "is-invalid": ""}}" name="stock" id="stock" value="{{ old('stock') ? old('stock') : $book['stock'] }}">                                 
                                <div class="invalid-feedback">                        
                                    {{$errors->first('stock')}}              
                                </div>   
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="category">Category</label>
                            </div>
                            <div class="col-md-8">    
                                @foreach($book->category as $category)       
                                    <span class="badge badge-primary">{{ $category->category_name }}  </span> 
                                @endforeach 
                                <select multiple='multiple' name="category[]" id="category" class="form-control {{$errors->first('category') ? "is-invalid": ""}}">        
                                    <option value="">Select a New Category</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->category_name }}</option> 
                                    @endforeach
                                    </select>     
                                <div class="invalid-feedback">
                                    {{$errors->first('category')}}   
                                </div>        
                            </div>   
                        </div>
                        <br>
                        <div class="row">     
                            <div class="col-md-3">                    
                                Cover                             
                            </div>                             
                            <div class="col-md-8">              
                                <img src="{{asset('storage/'.$book['cover'])}}" class="img-thumbnail" height="150px" width="150px" alt="">                
                                <div class="custom-file">                              
                                    <label for="cover" class="custom-file-label">Cover</label>         
                                    <input type="file" class="custom-file-input {{$errors->first('cover') ? "is-invalid": ""}}"  name="cover" id="cover">                 
                                    <div class="invalid-feedback">                 
                                        {{$errors->first('cover')}}               
                                    </div>                                 
                                </div>                             
                            </div>                         
                        </div>                         
                        <br>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/index.blade.php
@extends('templates.home')
@section('title')
    Book List
@endsection
@section('css')
    <style>
        body{
            padding-top: 30px;
        }
        th, td {
            padding: 10px;
            text-align: center;
        }
        td a{
            margin: 3px;
            align-content: center;
            color: white;
        }
        td a:hover{
            text-decoration: none;
        }
        td button{
            margin-top: 5px;
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <h3>Book List</h3><hr>
        <div class="row">
            <div class="col-md-7">
                <a class="btn btn-outline-primary " href="{{ route('books.create') }}">
                    <span data-feather="plus-circle"></span>
                    Add<span class="sr-only">(current)</span>
                </a>
            </div>
            <form action="{{ route('books.search','current()') }}">
                <div class="row">
                    <div class="col-md-15">
                        <input type="text" style="width: 320px" name="keyword" class="form-control" placeholder="Search books with title">
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary">
                            <span data-feather="search"></span> Search
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <br>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">          
                <strong>{{ session('status') }}</strong>       
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">       
                    <span aria-hidden="true">&times;</span>  
                </button>             
            </div>         
        @endif
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Price</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Cover</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($books as $book)
                        <tr>
                            <td>{{ $book['id'] }}</td>
                            <td>{{ $book['title'] }}</td>
                            <td>{{ $book['author'] }}</td>
                            <td>{{ $book['price'] }}</td>
                            <td>{{ $book['stock'] }}</td>
                            <td> 
                                @if($book['cover'])
                                    <img src="{{asset('storage/'.$book['cover'])}}" alt="" width="80px">
                                @else
                                    N/A
                                @endif                                    
                            </td>
                            <td>
                                <a class="btn-sm btn-primary" href="{{ route('books.show',$book['id']) }}">
                                <span data-feather="eye"></span>
                                Detail <span class="sr-only">(current)</span></a>
                                <a class="btn-sm btn-success d-inline" href="{{ route('books.edit',$book['id']) }}">
                                <span data-feather="edit-2"></span>
                                Edit <span class="sr-only">(current)</span></a>
                                <form class="d-inline"
                                    onsubmit="return confirm('Delete this book permanently?')"
                                    action="{{route('books.destroy', $book['id'])}}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger" value="Delete">
                                    <span data-feather="trash"></span>
                                    Delete <span class="sr-only">(current)</span></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                {{ $books->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/books/show.blade.php
@extends('templates.home')
@section('title')
    Detail Book
@endsection
@section('content')
    <h1>Detail Book </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width:70%; margin:auto; min-height:400px;">
        <div class="row " style="padding:25px">
            <div class="col-md-2 offset-md-5 offset-sm-4">
                <img src="{{ asset('storage/'.$book['cover']) }}" style="height:150px; width:150px;" class="rounded-circle" alt="">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <h3>{{ $book['title'] }}</h3>
            </div>
        </div>
        <hr>
        <br>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Author
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['author'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Publisher
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['publisher'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Description
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['description'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Price
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $book['price'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Stock
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['stock'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Category
            </div>
            <div class="col-md-4 col-sm-4 "> 
                @foreach($book->category as $category)       
                    <span class="badge badge-primary">{{ $category->category_name }}  </span> 
                @endforeach 
            </div>
            <br>
            <br>
            <br>
        </div>
    </div>
@endsection