routes/web.php
<?php

Route::get('/', function () {
    return view('templates/home');
})->name('home');

Route::resource('/users', 'UserController');
Route::get('/user', 'UserController@search')->name('users.search');

Route::resource('/categories', 'CategoryController');
Route::get('/category', 'CategoryController@search')->name('categories.search');

Route::resource('/books', 'BookController');
Route::get('/book', 'BookController@search')->name('books.search');

Route::resource('/orders', 'OrderController');
Route::get('/order', 'OrderController@search')->name('orders.search');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'category_name', 'description'
    ];

    public function book()     
    {         
        return $this->belongsToMany(Book::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request; 
use App\Category; 

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::paginate(5);
        return view('categories.index',compact('categories'));
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'category_name'=>'required|min:4|max:100|unique:categories',             
            'description'=>'required|max:200',                  
        ]); 

        Category::create([             
            'category_name'=>$request->category_name,             
            'description'=>$request->description,     
        ]);

        return redirect()->route('categories.create')->with('status','Category Successfully Created');
    }

    public function show($id)
    {
        $category = Category::findOrFail($id);         
        return view('categories.show',['category'=>$category]); 
    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);       
        return view('Categories.edit',['category'=>$category]); 
    }

    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id); 
        $request->validate([                         
            'description'=>'required|max:200',                     
        ]);  
        $update_category = Category::findOrFail($id);         
        $update_category->description = $request->get('description');
        $update_category->save();         
        return redirect()->route('categories.edit',['category'=>$category])->with('status','Category Successfully Updated'); 
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);  
        $category->delete();         
        return redirect()->route('categories.index')->with('status','Category Successfully Deleted'); 
    }

    public function search(Request $request)
    {
        $categories = Category::when($request->keyword, function ($query) use ($request) {
            $query->where('category_name', 'like', "%{$request->keyword}%");
        })->paginate(5);

        $categories->appends($request->only('keyword'));

        return view('categories.index', compact('categories'));
    }
}

resources/views/categories/create.blade.php
@extends('templates.home')
@section('title')
    Create Category
@endsection
@section('content')
    <div class="container" >
        <h3>Create Category</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">          
                <strong>{{ session('status') }}</strong>       
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">       
                    <span aria-hidden="true">&times;</span>  
                </button>             
            </div>         
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Category</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('categories.store') }}" class="form-group" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="category_name" >Category Name</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('category_name') }}" type="text" class="form-control {{$errors->first('category_name') ? "is-invalid": ""}}" name="category_name" id="category_name">          
                                <div class="invalid-feedback">                          
                                    {{$errors->first('category_name')}}                 
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">                             
                            <div class="col-md-3">                     
                                <label for="description">Description</label>  
                            </div>                            
                            <div class="col-md-8">             
                                <textarea name="description" class="form-control {{$errors->first('description') ? "is-invalid": ""}}" id="description" cols="20" rows="5">{{ old('description') }}</textarea>
                                <div class="invalid-feedback">              
                                    {{$errors->first('description')}}          
                                </div>                            
                            </div>                         
                        </div>                         
                        <br>       
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Category
@endsection
@section('content')
    <div class="container" >
        <h3>Form Edit Category</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">          
                <strong>{{ session('status') }}</strong>       
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">       
                    <span aria-hidden="true">&times;</span>  
                </button>             
            </div>         
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>{{ $category['category_name'] }}</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('categories.update',$category['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">                        
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="description" class="text-primary">Description</label>
                            </div>
                            <div class="col-md-8">
                                <textarea name="description" class="form-control {{$errors->first('description') ? "is-invalid": ""}}" id="description" cols="20" rows="5">{{ old('description') ? old('description') : $category['description'] }}</textarea>                  
                                <div class="invalid-feedback">   
                                    {{$errors->first('description')}}                 
                                </div> 
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('templates.home')
@section('title')
    Category List
@endsection
@section('css')
    <style>
        body{
            padding-top: 30px;
        }
        th, td {
            padding: 10px;
            text-align: center;
        }
        td a{
            margin: 3px;
            align-content: center;
            color: white;
        }
        td a:hover{
            text-decoration: none;
        }
        td button{
            margin-top: 5px;
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <h3>Category List</h3><hr>
        <div class="row">
            <div class="col-md-7">
                <a class="btn btn-outline-primary " href="{{ route('categories.create') }}">
                    <span data-feather="plus-circle"></span>
                    Add<span class="sr-only">(current)</span>
                </a>
            </div>
            <form action="{{ route('categories.search','current()') }}">
                <div class="row">
                    <div class="col-md-15">
                        <input type="text" style="width: 320px" name="keyword" class="form-control" placeholder="Search categories with category name">
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary">
                            <span data-feather="search"></span> Search
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <br>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">          
                <strong>{{ session('status') }}</strong>       
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">       
                    <span aria-hidden="true">&times;</span>  
                </button>             
            </div>         
        @endif
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">ID</th>
                        <th scope="col">Category Name</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category['id'] }}</td>
                            <td>{{ $category['category_name'] }}</td>
                            <td>
                                <a class="btn-sm btn-primary" href="{{ route('categories.show',$category['id']) }}">
                                <span data-feather="eye"></span>
                                Detail <span class="sr-only">(current)</span></a>
                                <a class="btn-sm btn-success d-inline" href="{{ route('categories.edit',$category['id']) }}">
                                <span data-feather="edit-2"></span>
                                Edit <span class="sr-only">(current)</span></a>
                                <form class="d-inline"
                                    onsubmit="return confirm('Delete this category permanently?')"
                                    action="{{route('categories.destroy', $category['id'])}}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger" value="Delete">
                                    <span data-feather="trash"></span>
                                    Delete <span class="sr-only">(current)</span></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                {{ $categories->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/categories/show.blade.php
@extends('templates.home')
@section('title')
    Detail Category
@endsection
@section('content')
    <h1>Detail Category </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width:70%; margin:auto; min-height:200px;">
        <br>
        <div class="row">
            <div class="col-md-12 text-center">
                <h3>{{ $category['category_name'] }}</h3>
            </div>
        </div>
        <hr>
        <br>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Description
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $category['description'] }}
            </div>
            <br>
        </div>
    </div>
@endsection