routes/web.php
<?php

Route::get('/', function () {
    return view('templates/home');
})->name('home');

Route::resource('/users', 'UserController');
Route::get('/user', 'UserController@search')->name('users.search');

Route::resource('/categories', 'CategoryController');
Route::get('/category', 'CategoryController@search')->name('categories.search');

Route::resource('/books', 'BookController');
Route::get('/book', 'BookController@search')->name('books.search');

Route::resource('/orders', 'OrderController');
Route::get('/order', 'OrderController@search')->name('orders.search');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Order extends Model
{
    protected $fillable=[         
        'user_id','total_price','invoice_number','status'     
    ]; 
 
    public function user()     
    {         
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request; 
use App\Order; 
use App\User; 

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::paginate(5);
        return view('orders.index',compact('orders'));
    }

    public function create()
    {
        $users = User::all();         
        return view('orders.create',['users'=>$users]); 
    }

    public function store(Request $request)
    {
        $request->validate([
            'user_id'=>'required',             
            'total_price'=>'required',             
            'invoice_number'=>'required|min:8|unique:orders',             
            'status'=> 'required',  
        ]); 

        Order::create([
            'user_id'=>$request->user_id,             
            'total_price'=>$request->total_price,             
            'invoice_number'=>$request->invoice_number,             
            'status'=>$request->status, 
        ]);    
        return redirect()->route('orders.create')->with('status','Order Succesfully Created');     
    } 

    public function show($id)
    {
        $order = Order::findOrFail($id);         
        return view('orders.show',['order'=>$order]); 
    }

    public function edit($id)
    {
        $order = Order::findOrFail($id); 
        $users = User::all();         
        return view('orders.edit',['order'=>$order,'users'=>$users]); 
    }

    public function update(Request $request, $id)
    {
        $order = Order::findOrFail($id); 
        $request->validate([
            'user_id'=>'required',             
            'total_price'=>'required',                
            'status'=> 'required',  
        ]); 
        $update_order = Order::findOrFail($id);         
        $update_order->user_id = $request->get('user_id');
        $update_order->total_price = $request->get('total_price');         
        $update_order->status = $request->get('status');          
        $update_order->save();   
        return redirect()->route('orders.edit',['order'=>$order])->with('status','Order Successfully Updated'); 
    }

    public function destroy($id)
    {
        $order = Order::findOrFail($id);  
        $order->delete();         
        return redirect()->route('orders.index')->with('status','Order Successfully Deleted'); 
    }

    public function search(Request $request)
    {
        $orders = Order::when($request->keyword, function ($query) use ($request) {
            $query->where('status', 'like', "%{$request->keyword2}%")
                ->where('invoice_number', 'like', "%{$request->keyword}%");
        })->paginate(5);

        $orders->appends($request->only('keyword'));

        return view('orders.index', compact('orders'));
    }
}

resources/views/orders/create.blade.php
@extends('templates.home')
@section('title')
    Create Order
@endsection
@section('content')
    <div class="container" >
        <h3>Create Order</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">     
                <strong>{{ session('status') }}</strong>  
                <button type="button" class="close" data-dismiss="alert" arialabel="Close">       
                    <span aria-hidden="true">&times;</span> 
                </button>             
            </div>         
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Order</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('orders.store') }}" class="form-group" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="invoice_number" >Invoice Number</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('invoice_number') }}" type="text" class="form-control {{ $errors->first('invoice_number')? "is-invalid": "" }}" name="invoice_number" id="invoice_number">        
                                <div class="invalid-feedback">   
                                    {{$errors->first('invoice_number')}} 
                                </div>
                            </div>        
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="total">Total Price</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('total_price') }}" type="number" class="form-control {{ $errors->first('total_price')? "is-invalid": "" }}" name="total_price" id="total_price">        
                                <div class="invalid-feedback">   
                                    {{$errors->first('total_price')}} 
                                </div>
                            </div> 
                        </div>
                        <br>
                        <div class="row">             
                            <div class="col-md-3">   
                                <label for="user_id">User</label>                
                            </div>   
                            <div class="col-md-8">    
                                <select name="user_id" id="user_id" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">        
                                    <option value="">Select User</option>           
                                    @foreach ($users as $user)    
                                        <option value="{{ $user->id }}">{{ $user->username }}</option> 
                                    @endforeach  
                                </select>         
                                <div class="invalid-feedback">
                                    {{$errors->first('user_id')}}   
                                </div>                 
                            </div>                      
                        </div>        
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="status">Status</label>
                            </div>
                            <div class="col-md-8">
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="submit" name="status" class="custom-control-input" value="SUBMIT">
                                    <label class="custom-control-label" for="submit">SUBMIT</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="process" name="status" class="custom-control-input" value="PROCESS">
                                    <label class="custom-control-label" for="process">PROCESS</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="finish" name="status" class="custom-control-input" value="FINISH">
                                    <label class="custom-control-label" for="finish">FINISH</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" id="cancel" name="status" class="custom-control-input" value="CANCEL">
                                    <label class="custom-control-label" for="cancel">CANCEL</label>
                                </div>
                            </div>
                        </div> 
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Order
@endsection
@section('content')
    <div class="container" >
        <h3>Form Edit Order</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">          
                <strong>{{ session('status') }}</strong>       
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">       
                    <span aria-hidden="true">&times;</span>  
                </button>             
            </div>         
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>{{ $order['invoice_number'] }}</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('orders.update',$order['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">                        
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="total" class="text-primary">Tottal Price</label>
                            </div>
                            <div class="col-md-8">
                                <input type="number" class="form-control {{$errors->first('total_price') ? "is-invalid": ""}}" name="total_price" id="total_price" value="{{ old('total_price') ? old('total_price') : $order['total_price'] }}">                                 
                                <div class="invalid-feedback">                        
                                    {{$errors->first('total_price')}}              
                                </div>               
                            </div>
                        </div>
                        <br>
                        <div class="row">                             
                            <div class="col-md-3">                                 
                                <label for="user_id">User</label>                   
                            </div>                             
                            <div class="col-md-8">             
                                <select name="user_id" id="user_id" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">                    
                                    <option value="">Select User</option>
                                    @foreach ($users as $user)          
                                        <option value="{{ $user->id }}" {{ $order->user_id==$user->id ? "selected":'' }}>{{ $user->username }}</option>            
                                    @endforeach                                 
                                </select>                                 
                                <div class="invalid-feedback">            
                                    {{$errors->first('user_id')}}        
                                </div>                             
                            </div>                         
                        </div>                         
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="status" class="text-primary">Status</label>
                            </div>
                            <div class="col-md-8">
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input {{ $order['status'] == "SUBMIT" ? 'checked':'' }}
                                        type="radio" id="submit" name="status" class="custom-control-input" value="SUBMIT">
                                    <label class="custom-control-label" for="submit">SUBMIT</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input {{ $order['status'] == "PROCESS" ? 'checked':'' }}
                                        type="radio" id="process" name="status" class="custom-control-input" value="PROCESS">
                                    <label class="custom-control-label" for="process">PROCESS</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input {{ $order['status'] == "FINISH" ? 'checked':'' }}
                                        type="radio" id="finish" name="status" class="custom-control-input" value="FINISH">
                                    <label class="custom-control-label" for="finish">FINISH</label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input {{ $order['status'] == "CANCEL" ? 'checked':'' }}
                                        type="radio" id="cancel" name="status" class="custom-control-input" value="CANCEL">
                                    <label class="custom-control-label" for="cancel">CANCEL</label>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/index.blade.php
@extends('templates.home')
@section('title')
    Order List
@endsection
@section('css')
    <style>
        body{
            padding-top: 30px;
        }
        th, td {
            padding: 10px;
            text-align: center;
        }
        td a{
            margin: 3px;
            align-content: center;
            color: white;
        }
        td a:hover{
            text-decoration: none;
        }
        td button{
            margin-top: 5px;
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <h3>Order List</h3><hr>
        <div class="row">
            <div class="col-md-4">
                <a class="btn btn-outline-primary " href="{{ route('orders.create') }}">
                    <span data-feather="plus-circle"></span>
                    Add<span class="sr-only">(current)</span>
                </a>
            </div>
            <div class="col-md-7">
                <form action=" {{ route('orders.search') }} " method="get">
                    <div class="input-group custom-search-form">
                        <input type="text" name="keyword" placeholder="Search with Invoice Number" class="form-control" id="search">
                        <select name="keyword2" class="col-sm-2">
                            <option value="">
                                ALL
                            </option>
                            <option value="SUBMIT">
                                SUBMIT
                            </option>
                            <option value="PROCESS">
                                PROCESS
                            </option>
                            <option value="FINISH">
                                FINISH
                            </option>
                            <option value="CANCEL">
                                CANCEL
                            </option>
                        </select>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary">
                                <span data-feather="search"></span> Search
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">          
                <strong>{{ session('status') }}</strong>       
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">       
                    <span aria-hidden="true">&times;</span>  
                </button>             
            </div>         
        @endif
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">ID</th>
                        <th scope="col">Invoice Number</th>
                        <th scope="col">Total Price</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($orders as $order)
                        <tr>
                            <td>{{ $order['id'] }}</td>
                            <td>{{ $order['invoice_number'] }}</td>
                            <td>{{ $order['total_price'] }}</td>
                            <td>
                                @if ( $order['status'] == "SUBMIT" )
                                    <span class="badge badge-primary""> {{ $order['status'] }} </span>
                                @elseif ( $order['status'] == "PROCESS" )
                                    <span class="badge badge-warning""> {{ $order['status'] }} </span>
                                @elseif ( $order['status'] == "FINISH" )
                                    <span class="badge badge-success""> {{ $order['status'] }} </span>
                                @else 
                                    <span class="badge badge-danger""> {{ $order['status'] }} </span>
                                @endif
                            </td>
                            <td>
                                <a class="btn-sm btn-primary" href="{{ route('orders.show',$order['id']) }}">
                                <span data-feather="eye"></span>
                                Detail <span class="sr-only">(current)</span></a>
                                <a class="btn-sm btn-success d-inline" href="{{ route('orders.edit',$order['id']) }}">
                                <span data-feather="edit-2"></span>
                                Edit <span class="sr-only">(current)</span></a>
                                <form class="d-inline"
                                    onsubmit="return confirm('Delete this order permanently?')"
                                    action="{{route('orders.destroy', $order['id'])}}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger" value="Delete">
                                    <span data-feather="trash"></span>
                                    Delete <span class="sr-only">(current)</span></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                {{ $orders->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/orders/show.blade.php
@extends('templates.home')
@section('title')
    Detail Order
@endsection
@section('content')
    <h1>Detail Order </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width:70%; margin:auto; min-height:200px;">
        <br>
        <div class="row">
            <div class="col-md-12 text-center">
                <h3>{{ $order['invoice_number'] }}</h3>
            </div>
        </div>
        <hr>
        <br>
        <div class="row"> 
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">             
                User           
            </div> 
            <div class="col-md-4 col-sm-4">             
                {{ $order->user->username }}
            </div>                 
            <br>             
        </div>  
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Total Price
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $order['total_price'] }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Status
            </div>
            <div class="col-md-4 col-sm-4 ">
                @if ( $order['status'] == "SUBMIT" )
                    <span class="badge badge-warning""> {{ $order['status'] }} </span>
                @elseif ( $order['status'] == "PROCESS" )
                    <span class="badge badge-primary""> {{ $order['status'] }} </span>
                @elseif ( $order['status'] == "FINISH" )
                    <span class="badge badge-success""> {{ $order['status'] }} </span>
                @else 
                    <span class="badge badge-danger""> {{ $order['status'] }} </span>
                @endif
            </div>
            <br>
        </div>
    </div>
@endsection